In [1]:
# user input
user_input = input('Man kan använda prompts som parameter: ')
print(user_input)

In [1]:
# att hämta intervaller
string = 'monty'
interval = string[0:4]
print(interval)

mont


In [12]:
# att räkna med vektorer och matriser som i linjär algebra görs med numpy

import numpy as np

vektor1 = [1, 2, 3]
vektor2 = [4, 5, 6]

vektor1 = np.array(vektor1)
vektor2 = np.array(vektor2)

sum = vektor1 + vektor2
print('vektor 1: ' + str(vektor1) + '\nvektor 2: ' + str(vektor2)  + '\nsumma: ' + str(sum))

#---------Matriser---------#

matrix = np.matrix([[1,2,3], [4,5,6], [7,8,9]])
print(matrix)
print(matrix*2)
print(matrix**2)
print(matrix/2)
print(vektor2*matrix)

vektor 1: [1 2 3]
vektor 2: [4 5 6]
summa: [5 7 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]
[[66 81 96]]


In [16]:
# att skapa intervaller

import numpy as np

array = np.arange(10, 100, 5) #arange(start, stop, step)
print(array)

# eller linspace

array = np.linspace(1, 10, 5) #linspace(start, stop, antal element)
print(array)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
[ 1.    3.25  5.5   7.75 10.  ]


In [2]:
# plotta en funktion

import numpy as np
import matplotlib.pyplot as plt

def f(x):
    return np.sin(x)
x = np.linspace(1, 10, 50)

plt.plot(x, f(x))

